strictness: high
test-warnings: true
doc-warnings: false

ignore-paths:
  - tests
  - famapy/metamodels/fm_metamodel/transformations/uvl_parser/UVLLexer.py
  - famapy/metamodels/fm_metamodel/transformations/uvl_parser/UVLListener.py
  - famapy/metamodels/fm_metamodel/transformations/uvl_parser/UVLParser.py

pep8:
  options:
    max-line-length: 100

pylint:
  disable:
    - super-init-not-called
    - unsubscriptable-object

mccabe:
  run: true
